# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: automate test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
   
  workflow_dispatch:
       
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.0'

#      - name: run analyze
#        run: flutter analyze

      - name: Get all Flutter Packages
        run: flutter pub get
        
      - name: Format Code
        run: dart format .

      - name: Run Flutter Test
        run: flutter test
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

